parameters:
  WebAppName: ''

jobs: 
 - job: Deploy
   steps:
   - task: AzureRmWebAppDeployment@4
     inputs:
       ConnectionType: 'AzureRM'
       azureSubscription: 'Azure'
       appType: 'webApp'
       WebAppName: ${{ parameters.WebAppName }}
       packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
